name: Playground Code Quality

on:
  pull_request:
    paths:
      - examples/playground/**

defaults:
  run:
    working-directory: ./examples/playground

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: "**/pnpm-lock.yaml"
      - run: pnpm pnpm:devPreinstall
      - run: pnpm install
      - run: "pnpm check:types"
      - run: "pnpm check:lint"
      - run: "pnpm check:format"

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: "**/pnpm-lock.yaml"
      - run: pnpm pnpm:devPreinstall
      - run: pnpm install
      - run: "pnpm test:unit"
      - run: pnpm exec playwright install --with-deps
      - run: "pnpm test:e2e"
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
